name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Package
      run: |
        mkdir -p Payload
        echo "ProxyX" > Payload/info.txt
        zip -r ProxyX.ipa Payload/
    - uses: actions/upload-artifact@v3
      with:
        name: ProxyX-IPA
        path: ProxyX.ipa
